import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { CaseComparison } from "@/components/CaseComparison";
import { StructuredData } from "@/components/StructuredData";
import { articleSchema, getSeoPage, pageMetadata } from "@/lib/seo/content-registry";
const page=getSeoPage("/examples/skincare-package-crop-review");
export const metadata:Metadata=pageMetadata(page);
export default function Page(){return <main className="content-page"><StructuredData data={articleSchema(page)}/><div className="content-container"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Examples",href:"/examples"},{label:"Skincare crop review",href:page.route}]}/><header className="content-hero content-hero-compact"><p className="eyebrow">Controlled skincare observability example</p><h1>{page.h1}</h1><p className="content-deck">The close crop preserves the logo and key front text, but excludes the lower package and twist component. Recognizing the product is not the same as verifying the complete package.</p></header><CaseComparison original={{src:"/examples/skincare-crop-observability/original.png",alt:"Complete approved SOLVANE sun stick",label:"Approved original",detail:"Full package and lower control visible"}} candidate={{src:"/examples/skincare-crop-observability/candidate.png",alt:"Close crop of the upper SOLVANE sun stick",label:"Image to check",detail:"Lower package outside the frame"}}/><section className="article-section"><h2>Why the result is REVIEW</h2><div className="case-fact-grid"><div><span>Verified region</span><strong>Logo and visible front text</strong></div><div><span>Observed decision</span><strong>REVIEW</strong></div><div><span>Missing evidence</span><strong>Lower component and full silhouette</strong></div></div><p>The crop can support a match for corresponding readable regions, but it cannot prove that hidden packaging and components remain unchanged. The safe next action is to request a complete candidate rather than infer either PASS or FAIL.</p></section><section className="article-section"><h2>Evidence language matters</h2><p>Sub-results should say that visible regions match, not that the entire product is verified. Pairvu treats this wording consistency as a continuing quality target while the overall REVIEW decision correctly prevents publication without enough coverage.</p></section><section className="article-section article-cta"><h2>Request a complete product view</h2><p>Capture the full package, its closure, base, controls, and identity-bearing label regions before approving the image.</p><div className="content-actions"><Link className="primary-link-button" href="/#checker">Check image</Link><Link className="text-link" href="/checks/product-image-observability">Review observability guidance</Link></div></section></div></main>}
