import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { CaseComparison } from "@/components/CaseComparison";
import { StructuredData } from "@/components/StructuredData";
import { articleSchema, getSeoPage, pageMetadata } from "@/lib/seo/content-registry";

const page = getSeoPage("/examples/laundry-sheets-scent-count-change");
export const metadata: Metadata = pageMetadata(page);

export default function LaundrySheetsScentCountChangePage() {
  return <main className="content-page"><StructuredData data={articleSchema(page)} /><div className="content-container">
    <Breadcrumbs items={[{label:"Home",href:"/"},{label:"Examples",href:"/examples"},{label:"Laundry-sheets variant and count",href:page.route}]} />
    <header className="content-hero content-hero-compact"><p className="eyebrow">Controlled household-product example</p><h1>{page.h1}</h1><p className="content-deck">The candidate keeps the FOLDWELL brand, folded-sheet symbol, sea-glass carton, cream panel, single-package count, flap, spine, and UP TO 60 LOADS claim, but changes two sellable-product attributes: FRESH LINEN becomes UNSCENTED and 30 SHEETS becomes 20 SHEETS.</p><p className="category-audience">This is a controlled comparison example built from founder-reviewed Pairvu output. It is not a customer case study, benchmark, certification, or statistical performance claim.</p></header>
    <CaseComparison original={{src:"/examples/foldwell-scent-count-change/original.png",alt:"Approved FOLDWELL Fresh Linen laundry sheets carton labeled 30 sheets",label:"Approved original",detail:"FRESH LINEN, 30 SHEETS"}} candidate={{src:"/examples/foldwell-scent-count-change/candidate.png",alt:"Candidate FOLDWELL Unscented laundry sheets carton labeled 20 sheets",label:"Image to check",detail:"UNSCENTED, 20 SHEETS"}} />
    <section className="article-section"><h2>Expected and observed verdict</h2><div className="case-fact-grid"><div><span>Expected verdict</span><strong>FAIL</strong></div><div><span>Observed verdict</span><strong>FAIL</strong></div><div><span>Controlled condition</span><strong>Scent variant and sheet count changed</strong></div></div><p>The observed verdict matched the expected outcome. Pairvu identified a visible-text and printed-value change rather than treating the familiar carton design as proof of the same SKU.</p></section>
    <section className="article-section"><h2>What changed and why the verdict matters</h2><p>FRESH LINEN became UNSCENTED and 30 SHEETS became 20 SHEETS. Matching artwork and package structure do not make two household-product variants interchangeable. The scent wording identifies the formula variant, while the printed sheet count changes the amount offered. Either confirmed difference affects the sellable product represented by the image and should stop publication until corrected.</p></section>
    <section className="article-section"><h2>What stayed stable</h2><ul className="check-list"><li>The FOLDWELL wordmark and folded-sheet symbol remain visible and aligned.</li><li>Both images show one complete rigid book-style carton.</li><li>The sea-glass green body, cream panel, front flap, spine, thumb notch, and silhouette remain consistent.</li><li>The LAUNDRY SHEETS and UP TO 60 LOADS wording remains unchanged.</li></ul></section>
    <section className="article-section"><h2>Why observability was sufficient</h2><p>Both images show the same corresponding front face at readable resolution. The changed scent and sheet-count lines are unobstructed, while the logo, load claim, colors, components, and full carton boundary remain available as stable controls. This is confirmed change evidence, not a REVIEW caused by hidden or ambiguous text.</p></section>
    <section className="article-section"><h2>How to review laundry-sheet variants</h2><p>Read the brand and product family first, then compare scent or formula wording, sheet count, load claim, carton construction, closure details, and complete package count. A familiar sustainable-paper design can still describe a different commercial offer when one short variant line or quantity changes.</p><div className="content-actions"><Link className="text-link" href="/checks/product-label-text">Review label-text checks</Link><Link className="text-link" href="/checks/product-quantity">Review quantity checks</Link><Link className="text-link" href="/categories/household-packaged-goods-image-qa">Use the household workflow</Link></div></section>
    <section className="article-section article-cta"><h2>Check household variants before publishing</h2><p>Compare the approved SKU with the final creative so a polished carton does not advertise the wrong scent, formula, count, or load claim.</p><div className="content-actions"><Link className="primary-link-button" href="/#checker">Check image</Link><Link className="text-link" href="/examples">See all comparison examples</Link></div></section>
  </div></main>;
}
