import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { CaseComparison } from "@/components/CaseComparison";
import { StructuredData } from "@/components/StructuredData";
import { articleSchema, getSeoPage, pageMetadata } from "@/lib/seo/content-registry";
const page=getSeoPage("/examples/skincare-product-background-change");
export const metadata:Metadata=pageMetadata(page);
export default function Page(){return <main className="content-page"><StructuredData data={articleSchema(page)}/><div className="content-container"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Examples",href:"/examples"},{label:"Skincare background change",href:page.route}]}/><header className="content-hero content-hero-compact"><p className="eyebrow">Controlled skincare hard negative</p><h1>{page.h1}</h1><p className="content-deck">The approved studio pack shot becomes a beach lifestyle image. The scene, scale, shadows, and props change while the observable SOLVANE product remains faithful.</p></header><CaseComparison original={{src:"/examples/skincare-background-change/original.png",alt:"Approved SOLVANE sunscreen stick on a studio background",label:"Approved original",detail:"Neutral studio pack shot"}} candidate={{src:"/examples/skincare-background-change/candidate.png",alt:"Same SOLVANE sunscreen stick in a beach setting",label:"Image to check",detail:"Beach scene; product unchanged"}}/><section className="article-section"><h2>Why the result is PASS</h2><div className="case-fact-grid"><div><span>Presentation change</span><strong>Background and composition</strong></div><div><span>Observed decision</span><strong>PASS</strong></div><div><span>Product identity</span><strong>Observable and matched</strong></div></div><p>A new setting is not a product defect. The logo, SPF 50+ value, wording, weight, colors, cap, twist control, count, and silhouette remain sufficiently visible. This case tests whether the checker can avoid a false alarm while still comparing the product itself.</p></section><section className="article-section"><h2>What this PASS does not certify</h2><p>PASS means the visible product remained faithful to the reference. It does not certify advertising claims, sun-protection compliance, marketplace acceptance, image rights, or whether the beach composition follows a brand campaign brief.</p></section><section className="article-section article-cta"><h2>Separate scene changes from product changes</h2><p>Use the approved pack as the anchor, then allow creative backgrounds only when the product remains observable and accurate.</p><div className="content-actions"><Link className="primary-link-button" href="/#checker">Check image</Link><Link className="text-link" href="/categories/skincare-product-image-qa">Use the skincare workflow</Link></div></section></div></main>}
