import type { Metadata, MetadataRoute } from "next";

export const SITE_URL = "https://pairvu.com";
export const SITE_NAME = "Pairvu";

export type SeoPageFamily = "product" | "market" | "hub" | "guide" | "case_study" | "category" | "check" | "use_case" | "legal";
export type SeoPageStatus = "published" | "planned" | "deferred";

export type SeoPage = {
  route: string;
  family: SeoPageFamily;
  status: SeoPageStatus;
  primaryKeyword: string;
  secondaryKeywords: string[];
  intent: string;
  parentRoute?: string;
  relatedRoutes: string[];
  title: string;
  h1: string;
  description: string;
  indexable: boolean;
  sitemapPriority: number;
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
  publishedAt?: string;
  updatedAt: string;
  evidenceSource: string;
  evidenceDate: string;
};

export type BreadcrumbItem = {
  label: string;
  href: string;
};

export const seoPages: readonly SeoPage[] = [
  {
    route: "/",
    family: "product",
    status: "published",
    primaryKeyword: "AI product image checker",
    secondaryKeywords: ["product image checker", "compare original and AI product image", "product visual QA"],
    intent: "Use a tool to compare an approved product image with an AI-generated or edited candidate.",
    relatedRoutes: ["/ai-product-photography", "/examples", "/categories", "/checks", "/guides", "/use-cases"],
    title: "Pairvu - AI Product Image Checker",
    h1: "Did AI change your product?",
    description:
      "Compare an AI-generated or edited product image with the original. Check visible changes to logos, label text, color, quantity, components, and packaging before publishing.",
    indexable: true,
    sitemapPriority: 1,
    changeFrequency: "weekly",
    publishedAt: "2026-07-29",
    updatedAt: "2026-07-29",
    evidenceSource: "Founder positioning decision and live SERP intent review",
    evidenceDate: "2026-07-29",
  },
  {
    route: "/ai-product-photography",
    family: "market",
    status: "published",
    primaryKeyword: "AI product photography",
    secondaryKeywords: ["AI product photos", "AI product photography quality control"],
    intent: "Understand AI product photography and how to keep generated or edited images accurate.",
    parentRoute: "/",
    relatedRoutes: ["/", "/examples", "/categories", "/guides/ai-product-photography-checklist", "/use-cases"],
    title: "AI Product Photography: Keep Product Images Accurate",
    h1: "AI Product Photography Without Changing the Product",
    description:
      "Learn how AI product photography works, where product details can drift, and how to compare AI product photos with an approved original before publishing.",
    indexable: true,
    sitemapPriority: 0.9,
    changeFrequency: "monthly",
    publishedAt: "2026-07-29",
    updatedAt: "2026-07-29",
    evidenceSource: "Live SERP review: market intent is dominated by generators and educational guides",
    evidenceDate: "2026-07-29",
  },
  {
    route: "/examples",
    family: "hub",
    status: "published",
    primaryKeyword: "AI product image changes",
    secondaryKeywords: ["AI changed product logo", "wrong text in AI product image", "product image comparison"],
    intent: "See the kinds of visible product changes that require pre-publish review.",
    parentRoute: "/",
    relatedRoutes: [
      "/",
      "/ai-product-photography",
      "/examples/logo-change-ai-product-image",
      "/examples/label-value-change-ai-product-image",
      "/examples/packaging-shape-change-ai-product-image",
      "/examples/color-change-ai-product-image",
      "/examples/background-change-ai-product-image",
      "/examples/missing-product-component-ai-image",
      "/examples/extra-product-component-ai-image",
      "/examples/product-count-change-ai-image",
      "/examples/identical-product-images-pass",
      "/examples/lighting-change-product-image",
      "/examples/shadow-reflection-change-product-image",
      "/examples/product-repositioning-perspective-change",
      "/examples/large-viewpoint-difference-product-image",
      "/examples/partially-hidden-product-logo",
      "/examples/unreadable-product-label-text",
      "/examples/partially-visible-product-image",
      "/examples/household-cleaner-capacity-change",
      "/examples/household-cleaner-background-change",
      "/categories",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Image Comparison Examples",
    h1: "Product Changes to Check in AI Images",
    description:
      "Explore the logo, label text, color, quantity, component, and packaging changes that can appear in AI-generated or edited product images.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-07-29",
    updatedAt: "2026-08-02",
    evidenceSource: "Pairvu M0 real-image behavior matrix",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/logo-change-ai-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI changed product logo",
    secondaryKeywords: ["AI product logo change", "compare product logo in AI image"],
    intent: "See a controlled comparison where an AI-edited product image changes a visible logo.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/label-value-change-ai-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Logo Change: Original vs Candidate",
    h1: "Logo Change in an AI Product Image",
    description:
      "See an original-versus-candidate cosmetics example where the visible logo changes from a crescent moon to a sun while the product text and packaging remain stable.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-07-30",
    updatedAt: "2026-07-30",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T02",
    evidenceDate: "2026-07-30",
  },
  {
    route: "/examples/label-value-change-ai-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI changed product label value",
    secondaryKeywords: ["wrong quantity in AI product image", "AI product label text change"],
    intent: "See a controlled comparison where a visible printed product value changes.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/logo-change-ai-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Label Value Change: 330 mL vs 500 mL",
    h1: "Printed Product Value Changed from 330 mL to 500 mL",
    description:
      "Compare two beverage images where the product, logo, and design remain stable but the visible capacity changes from 330 mL to 500 mL.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "yearly",
    publishedAt: "2026-07-30",
    updatedAt: "2026-07-30",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T01",
    evidenceDate: "2026-07-30",
  },
  {
    route: "/examples/packaging-shape-change-ai-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI changed product packaging shape",
    secondaryKeywords: ["AI product bottle shape change", "compare product packaging in AI image"],
    intent: "See a controlled comparison where an AI-edited product image changes packaging shape.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/logo-change-ai-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Packaging Shape Change Example",
    h1: "Packaging Shape Changed from Round to Rectangular",
    description:
      "See an original-versus-candidate shampoo comparison where the bottle changes from a rounded cylinder to a rectangular container while label content remains stable.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-07-30",
    updatedAt: "2026-07-30",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T03",
    evidenceDate: "2026-07-30",
  },
  {
    route: "/examples/color-change-ai-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI changed product color",
    secondaryKeywords: ["AI product label color change", "wrong product color in AI image"],
    intent: "See a controlled comparison where an AI-edited product image changes a prominent packaging color.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/logo-change-ai-product-image",
      "/examples/missing-product-component-ai-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Color Change: Original vs Candidate",
    h1: "Main Product Color Changed in an AI Image",
    description:
      "Compare an ELARA serum candidate where the cream-and-orange label becomes dark green while the product name, size, and bottle remain visible.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T04",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/examples/missing-product-component-ai-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI missing product component",
    secondaryKeywords: ["missing spray trigger in AI product image", "AI changed product components"],
    intent: "See a controlled comparison where an AI-edited product image is missing a major visible component.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/packaging-shape-change-ai-product-image",
      "/examples/product-count-change-ai-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Missing Product Component: Spray Trigger Removed",
    h1: "A Major Product Component Is Missing",
    description:
      "Compare a BRIGHTLEAF kitchen cleaner candidate where the white spray trigger is missing while the bottle and label remain visible.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T05",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/examples/background-change-ai-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI product image background change",
    secondaryKeywords: ["AI product photo background change", "AI product image background replacement"],
    intent: "See a controlled comparison where the product is unchanged but the background changes.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/color-change-ai-product-image",
      "/guides/keep-products-consistent-in-ai-images",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Background Change: Product Stays the Same",
    h1: "Background Changed, Product Still Matches",
    description:
      "Compare an ELARA serum image where the background changes from a neutral studio setting to a bright countertop scene while the visible product remains the same.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-01",
    updatedAt: "2026-08-01",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T09",
    evidenceDate: "2026-08-01",
  },
  {
    route: "/examples/extra-product-component-ai-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI added extra product component",
    secondaryKeywords: ["extra accessory in AI product image", "AI product component change"],
    intent: "See a controlled comparison where an extra visible component appears beside the approved product.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/missing-product-component-ai-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Added an Extra Product Component: Comparison Example",
    h1: "An Extra Product Component Appeared",
    description:
      "Compare an ELARA serum candidate that adds a separate white applicator while the bottle, logo, text, color, and packaging remain stable.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T06",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/identical-product-images-pass",
    family: "case_study",
    status: "published",
    primaryKeyword: "identical product image comparison",
    secondaryKeywords: ["same product image comparison", "unchanged AI product image"],
    intent: "See whether a product-image checker preserves a PASS when both input images are identical.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/background-change-ai-product-image",
      "/how-pairvu-works",
    ],
    title: "Identical Product Images: Pairvu PASS Example",
    h1: "Identical Product Images Should Pass",
    description:
      "See a controlled Pairvu comparison where the exact same NOVA FIZZ product image is used as both the original and candidate and receives a PASS.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T08",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/lighting-change-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "product image lighting change",
    secondaryKeywords: ["AI product photo lighting difference", "product still matches under different lighting"],
    intent: "See a controlled comparison where lighting changes but the visible product remains faithful.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/background-change-ai-product-image",
      "/examples/shadow-reflection-change-product-image",
    ],
    title: "Product Lighting Change: Product Still Matches",
    h1: "Lighting Changed, Product Still Matches",
    description:
      "Compare a MIREVA shampoo image under neutral and warmer light while its logo, wording, color, components, and packaging remain consistent.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T10",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/shadow-reflection-change-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "product image shadow reflection change",
    secondaryKeywords: ["AI product photo reflection difference", "product image shadow comparison"],
    intent: "See a controlled comparison where shadows and reflections change without changing the product.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/lighting-change-product-image",
      "/examples/background-change-ai-product-image",
      "/examples/product-repositioning-perspective-change",
    ],
    title: "Shadow and Reflection Change: Product Still Matches",
    h1: "Shadows Changed, Product Still Matches",
    description:
      "Compare a NOVA FIZZ can before and after stronger highlights and window shadows are added while the visible product remains unchanged.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T11",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/product-repositioning-perspective-change",
    family: "case_study",
    status: "published",
    primaryKeyword: "product image repositioning",
    secondaryKeywords: ["minor perspective change product image", "same product different position"],
    intent: "See controlled comparisons where product position and minor perspective change without changing product identity.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/lighting-change-product-image",
      "/examples/shadow-reflection-change-product-image",
      "/examples/large-viewpoint-difference-product-image",
    ],
    title: "Product Repositioning and Minor Perspective: PASS Example",
    h1: "Position Changed, Product Still Matches",
    description:
      "Compare GRAINLY product images where the same box is repositioned or shown at a slight angle while its logo, text, color, count, and packaging remain consistent.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T12 with two hard-negative variants",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/large-viewpoint-difference-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "large viewpoint difference product image",
    secondaryKeywords: ["front and back product image comparison", "product image different angle review"],
    intent: "Understand why different package faces can limit logo and label verification without proving a mismatch.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/product-repositioning-perspective-change",
      "/examples/partially-hidden-product-logo",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Large Viewpoint Difference: Product Image REVIEW Example",
    h1: "Different Product Viewpoints Need Review",
    description:
      "Compare front and back views of a BRIGHTLEAF cleaner bottle and see why logo and label fidelity remain unverified even when shape, color, count, and components match.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T13 after observability fix",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/partially-hidden-product-logo",
    family: "case_study",
    status: "published",
    primaryKeyword: "partially hidden product logo",
    secondaryKeywords: ["obscured product logo image", "product brand text covered in image"],
    intent: "Understand why a partially covered brand area should trigger review instead of a false logo mismatch.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/logo-change-ai-product-image",
      "/examples/large-viewpoint-difference-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Partially Hidden Product Logo: Visibility REVIEW Example",
    h1: "A Product Logo Is Partially Hidden",
    description:
      "Compare a NOVA FIZZ can before and after a sticker covers part of its logo and brand name, creating a visibility limitation rather than a confirmed product change.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T14 after observability fix",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/unreadable-product-label-text",
    family: "case_study",
    status: "published",
    primaryKeyword: "unreadable product label text",
    secondaryKeywords: ["blurry product label text", "pixelated text in AI product image"],
    intent: "Understand why blurry or pixelated identity text should be reviewed instead of assumed to match.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/label-value-change-ai-product-image",
      "/examples/partially-hidden-product-logo",
      "/examples/partially-visible-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Unreadable Product Label Text: Visibility REVIEW Example",
    h1: "Product Label Text Is Unreadable",
    description:
      "Compare a readable GRAINLY package with a candidate whose brand, product name, and printed value are pixelated, requiring review instead of an assumed text match.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T15 corrected unreadable-text variant",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/partially-visible-product-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "partially visible product image",
    secondaryKeywords: ["cropped product image comparison", "incomplete product coverage"],
    intent: "Understand why a cropped candidate may verify visible details but cannot support a full product PASS.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/packaging-shape-change-ai-product-image",
      "/examples/large-viewpoint-difference-product-image",
      "/examples/unreadable-product-label-text",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Partially Visible Product Image: Coverage REVIEW Example",
    h1: "Only Part of the Product Is Visible",
    description:
      "Compare a complete MIREVA shampoo image with a close crop that hides the lower label, printed value, bottle base, and full packaging silhouette.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-02",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T16 after coverage handling fix",
    evidenceDate: "2026-08-02",
  },
  {
    route: "/examples/product-count-change-ai-image",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI changed product count",
    secondaryKeywords: ["wrong quantity in AI product image", "AI added extra product package"],
    intent: "See a controlled comparison where an AI-edited product image changes the visible number of primary product units.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/label-value-change-ai-product-image",
      "/examples/missing-product-component-ai-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Count Change: One Box vs Two",
    h1: "Product Count Changed from One Box to Two",
    description:
      "Compare an AI product-image candidate that shows two GRAINLY food boxes where the approved original shows one, with the visible packaging design unchanged.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Founder-approved Pairvu controlled real-image fixture T07",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/examples/household-cleaner-capacity-change",
    family: "case_study",
    status: "published",
    primaryKeyword: "AI changed household cleaner capacity",
    secondaryKeywords: ["wrong cleaner bottle volume in AI image", "household product label value change"],
    intent: "See a controlled household-product comparison where an AI-edited image changes a readable capacity value.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/household-cleaner-background-change",
      "/examples/missing-product-component-ai-image",
      "/categories/household-packaged-goods-image-qa",
      "/checks/product-quantity",
    ],
    title: "Household Cleaner Capacity Change: 750 mL vs 500 mL",
    h1: "Household Cleaner Capacity Changed from 750 mL to 500 mL",
    description:
      "Compare an approved BRIGHTLEAF kitchen-cleaner image with a candidate whose readable capacity changes from 750 mL to 500 mL while the bottle and trigger remain stable.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-04",
    updatedAt: "2026-08-04",
    evidenceSource: "Founder-approved Pairvu controlled household real-image fixture HOUSEHOLD-01",
    evidenceDate: "2026-08-04",
  },
  {
    route: "/examples/household-cleaner-background-change",
    family: "case_study",
    status: "published",
    primaryKeyword: "household product background change",
    secondaryKeywords: ["AI cleaner product photo background change", "same household product different background"],
    intent: "See a controlled household-product comparison where only the environment changes and the product passes.",
    parentRoute: "/examples",
    relatedRoutes: [
      "/",
      "/examples",
      "/examples/household-cleaner-capacity-change",
      "/examples/large-viewpoint-difference-product-image",
      "/categories/household-packaged-goods-image-qa",
    ],
    title: "Household Product Background Change: PASS Example",
    h1: "Kitchen Background Changed, Household Product Passed",
    description:
      "Compare the same BRIGHTLEAF cleaner on a studio background and kitchen counter. The bottle, trigger, logo, text, color, and 750 mL value remain faithful.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-04",
    updatedAt: "2026-08-04",
    evidenceSource: "Founder-approved Pairvu controlled household real-image fixture HOUSEHOLD-02",
    evidenceDate: "2026-08-04",
  },
  {
    route: "/categories",
    family: "hub",
    status: "published",
    primaryKeyword: "product image QA by category",
    secondaryKeywords: ["CPG product image quality control", "AI product image review by category"],
    intent: "Find a category-specific workflow for checking visible product fidelity in AI-generated or edited images.",
    parentRoute: "/",
    relatedRoutes: [
      "/",
      "/examples",
      "/categories/cosmetics-product-image-qa",
      "/categories/beverage-product-image-qa",
      "/categories/personal-care-product-image-qa",
      "/categories/packaged-food-product-image-qa",
      "/categories/household-packaged-goods-image-qa",
      "/use-cases",
    ],
    title: "Product Image QA by Category | Pairvu",
    h1: "Product Image QA for Packaged Goods",
    description:
      "Use Pairvu's evidence-backed cosmetics, beverage, personal-care, packaged-food, and household packaged-goods workflows for reviewing AI product images.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-04",
    evidenceSource: "Founder-approved category hub with quality-gated public flagship pages",
    evidenceDate: "2026-08-04",
  },
  {
    route: "/checks",
    family: "hub",
    status: "published",
    primaryKeyword: "AI product image checks",
    secondaryKeywords: ["product image quality checks", "what to check in AI product images"],
    intent: "Choose an attribute-level method for reviewing a specific visible product detail in an AI-generated or edited image.",
    parentRoute: "/",
    relatedRoutes: [
      "/",
      "/checks/product-quantity",
      "/checks/product-label-text",
      "/checks/product-packaging",
      "/checks/product-logo",
      "/examples",
      "/categories",
      "/guides/ai-product-photography-checklist",
    ],
    title: "AI Product Image Checks for Visible Accuracy",
    h1: "What to Check in AI Product Images",
    description:
      "Use evidence-backed checks for product quantity, label text, packaging, logos, color, components, and visibility before publishing an AI-assisted product image.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Pairvu M0 check families and founder-approved controlled comparison library",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/checks/product-quantity",
    family: "check",
    status: "published",
    primaryKeyword: "check product quantity in AI images",
    secondaryKeywords: ["AI product quantity checker", "wrong product count in AI image", "check package quantity in product photo"],
    intent: "Understand how to verify printed quantity, visible package count, included units, and pack configuration in an AI product image.",
    parentRoute: "/checks",
    relatedRoutes: [
      "/",
      "/checks",
      "/examples/label-value-change-ai-product-image",
      "/examples/product-count-change-ai-image",
      "/examples/product-repositioning-perspective-change",
      "/examples/unreadable-product-label-text",
      "/categories/beverage-product-image-qa",
      "/categories/packaged-food-product-image-qa",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Check Product Quantity in AI Images | Pairvu",
    h1: "How to Check Product Quantity in AI Images",
    description:
      "Check printed amounts, visible package count, included units, and pack configuration in AI product images. Learn when quantity should pass, fail, or need review.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Pairvu cases T01, T07, T12, and T15 with current M0 decision behavior",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/checks/product-label-text",
    family: "check",
    status: "published",
    primaryKeyword: "check product label text in AI images",
    secondaryKeywords: ["AI product label text checker", "wrong packaging text in AI image", "compare product label text"],
    intent: "Understand how to verify visible brand wording, variants, claims, and printed values without treating hidden or unreadable text as a confirmed mismatch.",
    parentRoute: "/checks",
    relatedRoutes: [
      "/",
      "/checks",
      "/examples/label-value-change-ai-product-image",
      "/examples/identical-product-images-pass",
      "/examples/large-viewpoint-difference-product-image",
      "/examples/partially-visible-product-image",
      "/categories/cosmetics-product-image-qa",
      "/categories/personal-care-product-image-qa",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Check Product Label Text in AI Images | Pairvu",
    h1: "How to Check Product Label Text in AI Images",
    description:
      "Check visible brand names, variants, claims, and printed values in AI product images. Learn when label text should pass, fail, or need a clearer view.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Pairvu cases T01, T08, T13, and T16 with current M0 decision behavior",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/checks/product-packaging",
    family: "check",
    status: "published",
    primaryKeyword: "check product packaging in AI images",
    secondaryKeywords: ["AI product packaging checker", "wrong packaging shape in AI image", "compare product packaging images"],
    intent: "Understand how to verify visible container geometry, closures, major components, package construction, and complete silhouette in an AI product image.",
    parentRoute: "/checks",
    relatedRoutes: [
      "/",
      "/checks",
      "/examples/packaging-shape-change-ai-product-image",
      "/examples/missing-product-component-ai-image",
      "/examples/lighting-change-product-image",
      "/examples/partially-visible-product-image",
      "/categories/personal-care-product-image-qa",
      "/categories/cosmetics-product-image-qa",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Check Product Packaging in AI Images | Pairvu",
    h1: "How to Check Product Packaging in AI Images",
    description:
      "Check container shape, closures, dispensers, major parts, material cues, and package coverage in AI product images. Learn when packaging should pass, fail, or need review.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Pairvu cases T03, T05, T10, and T16 with current M0 decision behavior",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/checks/product-logo",
    family: "check",
    status: "published",
    primaryKeyword: "check product logo in AI images",
    secondaryKeywords: ["AI product logo checker", "wrong logo in AI image", "compare product logos in images"],
    intent: "Understand how to verify product symbols, wordmarks, lockups, placement, and logo observability in an AI-generated or edited product image.",
    parentRoute: "/checks",
    relatedRoutes: [
      "/",
      "/checks",
      "/examples/logo-change-ai-product-image",
      "/examples/background-change-ai-product-image",
      "/examples/shadow-reflection-change-product-image",
      "/examples/partially-hidden-product-logo",
      "/categories/cosmetics-product-image-qa",
      "/categories/beverage-product-image-qa",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Check Product Logos in AI Images | Pairvu",
    h1: "How to Check Product Logos in AI Images",
    description:
      "Check product symbols, wordmarks, lockups, placement, and logo visibility in AI product images. Separate confirmed identity changes from lighting and occlusion.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Pairvu cases T02, T09, T11, and T14 with current M0 decision behavior",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/categories/cosmetics-product-image-qa",
    family: "category",
    status: "published",
    primaryKeyword: "cosmetics product image QA",
    secondaryKeywords: ["AI cosmetics product image checker", "cosmetics packaging image comparison"],
    intent: "Check visible cosmetics packaging fidelity against an approved product image before publishing.",
    parentRoute: "/categories",
    relatedRoutes: [
      "/",
      "/categories",
      "/examples/logo-change-ai-product-image",
      "/examples/color-change-ai-product-image",
      "/examples/background-change-ai-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Cosmetics Product Image QA for AI Photos",
    h1: "Check AI Cosmetics Product Images",
    description:
      "Compare approved cosmetics packaging with AI-generated or edited images. Review visible logos, label text, colors, printed values, bottles, droppers, and applicators.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-02",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Cosmetics flagship backed by controlled change, hard-negative, and observability evidence",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/categories/beverage-product-image-qa",
    family: "category",
    status: "published",
    primaryKeyword: "beverage product image QA",
    secondaryKeywords: ["AI beverage image checker", "beverage packaging image comparison"],
    intent: "Check visible beverage packaging fidelity against an approved product image before publishing.",
    parentRoute: "/categories",
    relatedRoutes: [
      "/",
      "/categories",
      "/examples/label-value-change-ai-product-image",
      "/examples/shadow-reflection-change-product-image",
      "/examples/partially-hidden-product-logo",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Beverage Product Image QA for AI Photos",
    h1: "Check AI Beverage Product Images",
    description:
      "Compare approved beverage packaging with AI-generated or edited images. Review visible branding, flavor text, capacity, product count, colors, and container shape.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Beverage flagship backed by controlled capacity, reflection, and logo-observability cases T01, T11, and T14",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/categories/personal-care-product-image-qa",
    family: "category",
    status: "published",
    primaryKeyword: "personal care product image QA",
    secondaryKeywords: ["AI personal care image checker", "personal care packaging image comparison"],
    intent: "Check visible personal-care packaging fidelity against an approved product image before publishing.",
    parentRoute: "/categories",
    relatedRoutes: [
      "/",
      "/categories",
      "/examples/packaging-shape-change-ai-product-image",
      "/examples/lighting-change-product-image",
      "/examples/partially-visible-product-image",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Personal Care Product Image QA for AI Photos",
    h1: "Check AI Personal Care Product Images",
    description:
      "Compare approved personal-care packaging with AI-generated or edited images. Review visible labels, volume, bottle shape, pumps, caps, colors, and product coverage.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Personal Care flagship backed by controlled shape, lighting, and package-coverage cases T03, T10, and T16",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/categories/packaged-food-product-image-qa",
    family: "category",
    status: "published",
    primaryKeyword: "packaged food product image QA",
    secondaryKeywords: ["AI packaged food image checker", "food packaging image comparison"],
    intent: "Check visible packaged-food fidelity against an approved product image before publishing.",
    parentRoute: "/categories",
    relatedRoutes: [
      "/",
      "/categories",
      "/examples/product-count-change-ai-image",
      "/examples/product-repositioning-perspective-change",
      "/examples/unreadable-product-label-text",
      "/guides/ai-product-photography-checklist",
    ],
    title: "Packaged Food Product Image QA for AI Photos",
    h1: "Check AI Packaged Food Product Images",
    description:
      "Compare approved packaged-food images with AI-generated or edited candidates. Review visible brand and flavor text, net weight, product count, colors, and package shape.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    evidenceSource: "Founder-approved Packaged Food flagship backed by controlled count, perspective, and text-observability cases T07, T12, and T15",
    evidenceDate: "2026-08-03",
  },
  {
    route: "/categories/household-packaged-goods-image-qa",
    family: "category",
    status: "published",
    primaryKeyword: "household packaged goods product image QA",
    secondaryKeywords: ["AI household product image checker", "household cleaner packaging image comparison"],
    intent: "Check visible household packaged-goods fidelity against an approved product image before publishing.",
    parentRoute: "/categories",
    relatedRoutes: [
      "/",
      "/categories",
      "/examples/household-cleaner-capacity-change",
      "/examples/household-cleaner-background-change",
      "/examples/missing-product-component-ai-image",
      "/examples/large-viewpoint-difference-product-image",
      "/checks/product-quantity",
      "/checks/product-packaging",
    ],
    title: "Household Packaged Goods Image QA for AI Photos",
    h1: "Check AI Household Product Images",
    description:
      "Compare approved household packaged goods with AI-generated or edited images. Review visible labels, capacity, bottle color, triggers, closures, components, and package shape.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "yearly",
    publishedAt: "2026-08-04",
    updatedAt: "2026-08-04",
    evidenceSource: "Founder-approved Household flagship backed by capacity, background, missing-trigger, and viewpoint cases",
    evidenceDate: "2026-08-04",
  },
  {
    route: "/guides",
    family: "hub",
    status: "published",
    primaryKeyword: "AI product photography guides",
    secondaryKeywords: ["AI product image workflow", "product photo quality control"],
    intent: "Build a repeatable process for reviewing AI product images.",
    parentRoute: "/",
    relatedRoutes: ["/", "/ai-product-photography", "/guides/ai-product-photography-checklist"],
    title: "AI Product Photography Guides",
    h1: "Guides for Accurate AI Product Images",
    description:
      "Practical workflows for comparing original and AI product images, reviewing visible fidelity, and deciding when a product photo needs human review.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "monthly",
    publishedAt: "2026-07-29",
    updatedAt: "2026-07-29",
    evidenceSource: "Founder-approved pre-publish workflow",
    evidenceDate: "2026-07-29",
  },
  {
    route: "/guides/ai-product-photography-checklist",
    family: "guide",
    status: "published",
    primaryKeyword: "AI product photography checklist",
    secondaryKeywords: ["AI product photo checklist", "check AI product images before publishing"],
    intent: "Follow a checklist before publishing an AI-generated or edited product image.",
    parentRoute: "/guides",
    relatedRoutes: ["/", "/ai-product-photography", "/examples", "/use-cases"],
    title: "AI Product Photography Pre-Publish Checklist",
    h1: "AI Product Photography Pre-Publish Checklist",
    description:
      "Use this practical checklist to review logos, label text, color, product count, components, packaging, and observability before publishing an AI product photo.",
    indexable: true,
    sitemapPriority: 0.8,
    changeFrequency: "monthly",
    publishedAt: "2026-07-29",
    updatedAt: "2026-07-29",
    evidenceSource: "Pairvu M0 check families and real-image test results",
    evidenceDate: "2026-07-29",
  },
  {
    route: "/guides/compare-original-and-ai-product-images",
    family: "guide",
    status: "published",
    primaryKeyword: "compare original and AI product images",
    secondaryKeywords: ["compare product images before publishing", "AI product image comparison workflow"],
    intent: "Use a repeatable comparison workflow for an approved original and AI-generated or edited candidate.",
    parentRoute: "/guides",
    relatedRoutes: ["/", "/ai-product-photography", "/examples", "/guides/ai-product-photography-checklist"],
    title: "How to Compare Original and AI Product Images",
    h1: "How to Compare Original and AI Product Images",
    description:
      "Use a reference-based workflow to compare an approved product image with an AI-generated or edited candidate before publishing.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "monthly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Pairvu M0 comparison workflow and founder-approved public cases",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/guides/keep-products-consistent-in-ai-images",
    family: "guide",
    status: "published",
    primaryKeyword: "keep products consistent in AI images",
    secondaryKeywords: ["AI product image consistency", "consistent product images with AI"],
    intent: "Keep visible product identity stable across AI-assisted image variations without treating scene changes as product changes.",
    parentRoute: "/guides",
    relatedRoutes: ["/", "/ai-product-photography", "/examples", "/guides/ai-product-photography-checklist"],
    title: "How to Keep Products Consistent in AI Images",
    h1: "How to Keep Products Consistent in AI Images",
    description:
      "Keep logos, label text, color, product count, components, and packaging consistent when creating AI-assisted product images.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "monthly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Pairvu M0 check families and founder-approved public cases",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/use-cases",
    family: "hub",
    status: "published",
    primaryKeyword: "AI product image quality control",
    secondaryKeywords: ["ecommerce product image QA", "brand product photo review", "creative agency image QA"],
    intent: "Understand where a reference-based image check fits different publishing workflows.",
    parentRoute: "/",
    relatedRoutes: [
      "/",
      "/ai-product-photography",
      "/examples",
      "/guides/ai-product-photography-checklist",
      "/use-cases/ecommerce-product-image-qa",
      "/use-cases/amazon-product-image-qa",
      "/use-cases/shopify-product-image-qa",
    ],
    title: "AI Product Image Quality Control Use Cases",
    h1: "Where Pairvu Fits Before Publishing",
    description:
      "See how brands, creative teams, agencies, and commerce workflows can compare AI-generated product images with an approved original before publishing.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "monthly",
    publishedAt: "2026-07-29",
    updatedAt: "2026-07-29",
    evidenceSource: "Founder positioning and workflow review",
    evidenceDate: "2026-07-29",
  },
  {
    route: "/use-cases/ecommerce-product-image-qa",
    family: "use_case",
    status: "published",
    primaryKeyword: "ecommerce product image QA",
    secondaryKeywords: ["ecommerce image quality control", "check AI ecommerce product photos"],
    intent: "Add reference-based product fidelity review before ecommerce images are published.",
    parentRoute: "/use-cases",
    relatedRoutes: [
      "/",
      "/use-cases",
      "/examples",
      "/guides/ai-product-photography-checklist",
      "/use-cases/amazon-product-image-qa",
      "/use-cases/shopify-product-image-qa",
    ],
    title: "Ecommerce Product Image QA for AI-Assisted Photos",
    h1: "Ecommerce Product Image QA Before Publishing",
    description:
      "Use an approved product image as the reference, compare the final AI-assisted candidate, and route visible fidelity issues before catalog or campaign publishing.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "monthly",
    publishedAt: "2026-07-30",
    updatedAt: "2026-07-30",
    evidenceSource: "Founder-approved Pairvu pre-publish workflow",
    evidenceDate: "2026-07-30",
  },
  {
    route: "/use-cases/amazon-product-image-qa",
    family: "use_case",
    status: "published",
    primaryKeyword: "Amazon product image QA",
    secondaryKeywords: ["check AI Amazon product images", "Amazon seller product image accuracy"],
    intent: "Check product fidelity before applying Amazon's separate image and listing requirements.",
    parentRoute: "/use-cases",
    relatedRoutes: [
      "/",
      "/use-cases",
      "/examples",
      "/guides/ai-product-photography-checklist",
      "/use-cases/ecommerce-product-image-qa",
    ],
    title: "Amazon Product Image QA for AI-Assisted Images",
    h1: "Check Product Fidelity Before an Amazon Listing",
    description:
      "Compare an AI-assisted product image with an approved original before separately checking Amazon image requirements. Pairvu is not affiliated with Amazon.",
    indexable: true,
    sitemapPriority: 0.75,
    changeFrequency: "monthly",
    publishedAt: "2026-07-30",
    updatedAt: "2026-07-30",
    evidenceSource: "Amazon official listing guidance and Pairvu workflow review",
    evidenceDate: "2026-07-30",
  },
  {
    route: "/use-cases/shopify-product-image-qa",
    family: "use_case",
    status: "published",
    primaryKeyword: "Shopify product image QA",
    secondaryKeywords: ["check AI Shopify product images", "Shopify product media quality control"],
    intent: "Review product fidelity before adding final media to a Shopify product.",
    parentRoute: "/use-cases",
    relatedRoutes: [
      "/",
      "/use-cases",
      "/examples",
      "/guides/ai-product-photography-checklist",
      "/use-cases/ecommerce-product-image-qa",
    ],
    title: "Shopify Product Image QA Before Uploading Media",
    h1: "Check AI Product Images Before Adding Them to Shopify",
    description:
      "Compare final AI-assisted product images with approved originals before adding them to Shopify product media and publishing them across store surfaces.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "monthly",
    publishedAt: "2026-07-30",
    updatedAt: "2026-07-30",
    evidenceSource: "Shopify official product media documentation and Pairvu workflow review",
    evidenceDate: "2026-07-30",
  },
  {
    route: "/use-cases/brands",
    family: "use_case",
    status: "published",
    primaryKeyword: "brand product image quality control",
    secondaryKeywords: ["protect product identity in AI images", "brand image review workflow"],
    intent: "Add a visible-product fidelity checkpoint to a brand's AI-assisted image approval workflow.",
    parentRoute: "/use-cases",
    relatedRoutes: ["/", "/ai-product-photography", "/examples/logo-change-ai-product-image", "/guides/ai-product-photography-checklist"],
    title: "Brand Product Image Quality Control for AI-Assisted Photos",
    h1: "Protect Product Identity in AI-Assisted Brand Images",
    description:
      "Use an approved original to review visible brand identity, label text, product color, components, and packaging before AI-assisted images are published.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "monthly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Founder-approved Pairvu visual-fidelity workflow and public logo case",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/use-cases/creative-agencies",
    family: "use_case",
    status: "published",
    primaryKeyword: "creative agency product image QA",
    secondaryKeywords: ["AI product image QA for agencies", "review AI product visuals before client delivery"],
    intent: "Use client-approved product originals to review AI-assisted product visuals before delivery.",
    parentRoute: "/use-cases",
    relatedRoutes: ["/", "/ai-product-photography", "/examples/packaging-shape-change-ai-product-image", "/guides/compare-original-and-ai-product-images"],
    title: "Creative Agency Product Image QA for AI-Assisted Visuals",
    h1: "Review AI Product Visuals Before Client Delivery",
    description:
      "Use client-approved product originals to compare final AI-assisted visuals for visible identity, label, color, component, and packaging changes before delivery.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "monthly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Founder-approved Pairvu visual-fidelity workflow and public packaging case",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/how-pairvu-works",
    family: "guide",
    status: "published",
    primaryKeyword: "how Pairvu works",
    secondaryKeywords: ["reference based product image comparison", "AI product image QA method"],
    intent: "Understand Pairvu's reference-to-candidate product image comparison, verdicts, and limitations.",
    parentRoute: "/",
    relatedRoutes: ["/", "/ai-product-photography", "/examples", "/guides/ai-product-photography-checklist"],
    title: "How Pairvu Checks AI Product Images",
    h1: "How Pairvu Checks AI Product Images",
    description:
      "Learn how Pairvu compares an approved product image with an AI-generated or edited candidate and reports PASS, REVIEW, or FAIL.",
    indexable: true,
    sitemapPriority: 0.7,
    changeFrequency: "monthly",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    evidenceSource: "Pairvu M0 product semantics and published visual QA workflow",
    evidenceDate: "2026-07-31",
  },
  {
    route: "/privacy",
    family: "legal",
    status: "published",
    primaryKeyword: "Pairvu privacy",
    secondaryKeywords: [],
    intent: "Understand how Pairvu handles anonymous uploads and analysis data.",
    parentRoute: "/",
    relatedRoutes: ["/"],
    title: "Pairvu Privacy and Image Retention",
    h1: "Privacy",
    description:
      "Learn how Pairvu processes anonymous product images, limits retention to 24 hours, uses OpenAI for requested analysis, and protects session-bound results.",
    indexable: true,
    sitemapPriority: 0.3,
    changeFrequency: "yearly",
    publishedAt: "2026-07-27",
    updatedAt: "2026-07-29",
    evidenceSource: "Pairvu privacy and retention architecture",
    evidenceDate: "2026-07-29",
  },
];

export function getSeoPage(route: string): SeoPage {
  const page = seoPages.find((candidate) => candidate.route === route);
  if (!page) {
    throw new Error(`SEO registry has no page for route: ${route}`);
  }

  return page;
}

export function absoluteUrl(route: string) {
  return new URL(route, SITE_URL).toString();
}

export function pageMetadata(page: SeoPage): Metadata {
  return {
    title: {
      absolute: page.title,
    },
    description: page.description,
    alternates: {
      canonical: page.route,
    },
    openGraph: {
      type: "website",
      url: page.route,
      siteName: SITE_NAME,
      title: page.title,
      description: page.description,
    },
    twitter: {
      card: "summary_large_image",
      title: page.title,
      description: page.description,
    },
    robots: {
      index: page.indexable,
      follow: page.indexable,
    },
  };
}

export function breadcrumbSchema(items: BreadcrumbItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.label,
      item: absoluteUrl(item.href),
    })),
  };
}

export function websiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: SITE_URL,
    description: getSeoPage("/").description,
  };
}

export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_URL,
    logo: absoluteUrl("/icon.svg"),
    description:
      "Pairvu is an AI product image checker that compares an AI-generated or edited product image against an original reference image.",
  };
}

export function webApplicationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: SITE_NAME,
    url: SITE_URL,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
    description: getSeoPage("/").description,
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      description: "Capped anonymous public beta access",
    },
  };
}

export function articleSchema(page: SeoPage) {
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: page.h1,
    description: page.description,
    datePublished: page.publishedAt,
    dateModified: page.updatedAt,
    mainEntityOfPage: absoluteUrl(page.route),
    author: {
      "@type": "Organization",
      name: SITE_NAME,
      url: SITE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: SITE_NAME,
      url: SITE_URL,
      logo: {
        "@type": "ImageObject",
        url: absoluteUrl("/icon.svg"),
      },
    },
  };
}
