import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { CaseComparison } from "@/components/CaseComparison";
import { StructuredData } from "@/components/StructuredData";
import { articleSchema, getSeoPage, pageMetadata } from "@/lib/seo/content-registry";

const page = getSeoPage("/examples/laundry-sheets-background-change");
export const metadata: Metadata = pageMetadata(page);

export default function LaundrySheetsBackgroundChangePage() {
  return <main className="content-page"><StructuredData data={articleSchema(page)} /><div className="content-container">
    <Breadcrumbs items={[{label:"Home",href:"/"},{label:"Examples",href:"/examples"},{label:"Laundry-room background change",href:page.route}]} />
    <header className="content-hero content-hero-compact"><p className="eyebrow">Household-product hard-negative example</p><h1>{page.h1}</h1><p className="content-deck">The candidate moves the approved FOLDWELL carton from a neutral studio into a softly focused laundry room. The new tiles, shelving, towels, plant, countertop, scale, and shadow change the photograph without changing the observable product.</p><p className="category-audience">This is a controlled comparison example built from founder-reviewed Pairvu output. It is not a customer case study, benchmark, certification, or statistical performance claim.</p></header>
    <CaseComparison original={{src:"/examples/foldwell-background-change/original.png",alt:"Approved FOLDWELL Fresh Linen laundry sheets carton on a neutral studio background",label:"Approved original",detail:"Neutral studio pack shot"}} candidate={{src:"/examples/foldwell-background-change/candidate.png",alt:"Same FOLDWELL laundry sheets carton in a laundry-room scene",label:"Image to check",detail:"Same carton in a laundry room"}} />
    <section className="article-section"><h2>Expected and observed verdict</h2><div className="case-fact-grid"><div><span>Expected verdict</span><strong>PASS</strong></div><div><span>Observed verdict</span><strong>PASS</strong></div><div><span>Controlled condition</span><strong>Background and presentation changed</strong></div></div><p>The observed verdict matched the expected outcome. Pairvu found no product issue or observability limitation after the approved carton moved into a new scene.</p></section>
    <section className="article-section"><h2>What changed and why the verdict matters</h2><p>The tiles, shelving, towels, plant, countertop, product scale, lighting, and shadow changed. Those are presentation attributes, not part of the packaged product definition. A reliable approval workflow must allow useful creative variation without generating a false alarm whenever the observable product remains faithful.</p></section>
    <section className="article-section"><h2>What Pairvu verified</h2><ul className="check-list"><li>The FOLDWELL wordmark and folded-sheet symbol remain unchanged.</li><li>LAUNDRY SHEETS, FRESH LINEN, 30 SHEETS, and UP TO 60 LOADS remain readable.</li><li>One complete sea-glass green and cream carton appears in both images.</li><li>The rigid box, front flap, thumb notch, thin spine, and overall silhouette remain consistent.</li></ul></section>
    <section className="article-section"><h2>Why observability was sufficient</h2><p>The front logo, every identity-bearing text line, printed sheet count, load claim, colors, flap, spine, thumb notch, and complete silhouette remain visible in both images. The changed scene does not overlap or obscure the product, so the pair supports a direct attribute-by-attribute comparison.</p></section>
    <section className="article-section"><h2>Practical publishing guidance</h2><p>Approve the scene variation when product evidence remains faithful. Route the image to REVIEW instead when towels, baskets, appliances, reflections, shadows, a crop, or another prop hides identity text, count, closure details, color-bearing regions, or the complete carton boundary needed for approval.</p><div className="content-actions"><Link className="text-link" href="/checks/product-image-observability">Understand image observability</Link><Link className="text-link" href="/categories/household-packaged-goods-image-qa">Use the household workflow</Link></div></section>
    <section className="article-section article-cta"><h2>Allow creative settings without losing product control</h2><p>Use an approved pack shot to preserve the sellable household product while teams explore new rooms, surfaces, framing, and lighting.</p><div className="content-actions"><Link className="primary-link-button" href="/#checker">Check image</Link><Link className="text-link" href="/examples">See all comparison examples</Link></div></section>
  </div></main>;
}
