import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { CaseComparison } from "@/components/CaseComparison";
import { StructuredData } from "@/components/StructuredData";
import { articleSchema, getSeoPage, pageMetadata } from "@/lib/seo/content-registry";

const page = getSeoPage("/examples/laundry-sheets-back-view-review");
export const metadata: Metadata = pageMetadata(page);

export default function LaundrySheetsBackViewReviewPage() {
  return <main className="content-page"><StructuredData data={articleSchema(page)} /><div className="content-container">
    <Breadcrumbs items={[{label:"Home",href:"/"},{label:"Examples",href:"/examples"},{label:"Laundry-sheets back-view review",href:page.route}]} />
    <header className="content-hero content-hero-compact"><p className="eyebrow">Controlled household observability example</p><h1>{page.h1}</h1><p className="content-deck">The candidate shows the rear information panel of the same style of closed carton. Its color, rigid form, flap construction, and single-package count can be assessed, but the FOLDWELL logo, scent, sheet count, and load claim on the approved front face are turned away.</p><p className="category-audience">This is a controlled comparison example built from founder-reviewed Pairvu output. It is not a customer case study, benchmark, certification, or statistical performance claim.</p></header>
    <CaseComparison original={{src:"/examples/foldwell-back-view/original.png",alt:"Front of the approved FOLDWELL Fresh Linen 30-sheet laundry carton",label:"Approved original",detail:"Front identity panel visible"}} candidate={{src:"/examples/foldwell-back-view/candidate.png",alt:"Rear view of the FOLDWELL-style laundry sheets carton with instructions and icons",label:"Image to check",detail:"Rear information panel visible"}} />
    <section className="article-section"><h2>Expected and observed verdict</h2><div className="case-fact-grid"><div><span>Expected verdict</span><strong>REVIEW</strong></div><div><span>Observed verdict</span><strong>REVIEW</strong></div><div><span>Controlled condition</span><strong>Corresponding front face not visible</strong></div></div><p>The observed verdict matched the expected outcome. Pairvu reported no confirmed product difference and correctly routed the non-corresponding package faces to review.</p></section>
    <section className="article-section"><h2>What could not be verified and why it matters</h2><p>The rear view does not expose the FOLDWELL logo, LAUNDRY SHEETS product name, FRESH LINEN variant, 30 SHEETS quantity, or UP TO 60 LOADS claim visible on the approved front. A recognizable carton is not enough evidence to approve those customer-facing attributes. Treating hidden front details as either matched or changed would overstate what the pixels prove.</p></section>
    <section className="article-section"><h2>What can still be compared</h2><ul className="check-list"><li>Both images show one complete rigid rectangular carton.</li><li>The muted sea-glass green body and cream information panel remain consistent.</li><li>The thin box profile, rounded corners, flap construction, and overall silhouette correspond.</li><li>The candidate does not expose the corresponding front face needed to verify brand and sellable-product values.</li></ul></section>
    <section className="article-section"><h2>Observability explanation</h2><p>Directions, ingredients, cautions, and usage icons on the rear are complementary evidence, but they do not replace the identity and offer details on the front. The package color, rigid structure, flap, outline, and one-primary-package count remain observable; the brand and printed front values do not. REVIEW preserves that distinction without claiming the product changed.</p></section>
    <section className="article-section"><h2>Practical publishing guidance</h2><p>Request a candidate image showing the corresponding front face before approval. Keep the rear view as supporting evidence for package construction and rear-panel presentation, then compare the new front image against the approved original for logo, variant, sheet count, and load claim.</p><div className="content-actions"><Link className="text-link" href="/checks/product-image-observability">Review observability guidance</Link><Link className="text-link" href="/checks/product-label-text">Review label-text guidance</Link><Link className="text-link" href="/categories/household-packaged-goods-image-qa">Use the household workflow</Link></div></section>
    <section className="article-section article-cta"><h2>Request the missing package face</h2><p>Use a corresponding front view before approving identity-bearing artwork and printed values; keep the rear view as supporting evidence for package construction.</p><div className="content-actions"><Link className="primary-link-button" href="/#checker">Check image</Link><Link className="text-link" href="/examples">See all comparison examples</Link></div></section>
  </div></main>;
}
